<?php
$title = 'Delete book';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure you want to delete
    <?php echo $this->escapeHtml($book->title); ?>?
</p>

<?php
$url = $this->url('book',
    array(
        'action' => 'delete',
        'id' => $this->id,
    )
);
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" value="<?php echo (int) $book->id; ?>" name="id">
        <input type="submit" value="Yes" name="del">
        <input type="submit" value="No" name="del">
    </div>
</form>
